### PR TITLE
fix: dont always override namespace

### PR DESCRIPTION
**Pull request by cameronbraid**
The current promote process always sets OverrideNamespace, making it impossible to make it blank.

This PR allows multiple namespaces to be used by leaving OverrideNamespace blank and specifying a namespace per release.

It keeps old behaviour by initially setting OverrideNamespace when adding the first release and then leaving the release.namespace blank for any further additions

For example after first release in ns 'jx'

```
namespace: jx
repositories:
- name: dev
  url: http://chartmuseum-jx.34.78.195.22.nip.io
releases:
- chart: dev/myapp
  version: 1.2.3
  name: myapp-1-2-3
```

The user then can edit the file to move the toplevel namespace into the release as per :

```
namespace: ""
repositories:
- name: dev
  url: http://chartmuseum-jx.34.78.195.22.nip.io
releases:
- chart: dev/myapp
  version: 1.2.3
  name: myapp-1-2-3
  namespace: jx

```

Then a new release can be added for another namespace

```
namespace: ""
repositories:
- name: dev
  url: http://chartmuseum-jx.34.78.195.22.nip.io
releases:
- chart: dev/myapp
  version: 1.2.3
  name: myapp-1-2-3
  namespace: jx
- chart: dev/potato
  version: 1.2.3
  name: bar-1-2-3
  namespace: bar
```

Without this change, each time the helmfile is re-written to have the toplevel namespace set to 'jx'

### CODE REVIEW

**Comment by cameronbraid** [comment]
I am also thinking about how to define the namespace for a release to go into before the release happens

One idea could be to enhance the _per env promote.yaml_ file like https://github.com/jenkins-x/jx-promote/pull/263

given the following nested helmfile 

```
namespace: jx
repositories:
- name: dev
  url: https://chartmuseum-dev.drivenow.com.au
```

the following config could be used to define the release template for dev/foo :

```
apiVersion: promote.jenkins-x.io/v1alpha1
kind: HelmfilePromote
spec:
  releaseTemplates:
    dev/foo:
      namespace: bar
      values: ["bar-values.yaml"]
```

so that when promotion happens the helmfile is rewritten by first loading the releaseTempalte, then applying the promotion change which results in :

```
namespace: jx
repositories:
- name: dev
  url: https://chartmuseum-dev.drivenow.com.au
releases:
- chart: dev/foo
  version: 0.0.1
  name: foo
  namespace: bar
  values:
  - jx-values.yaml
  - bar-values.yaml

```

**Comment by jstrachan** [comment]
BTW I really like the idea of being able to define inside an app's repo, more configuration for how a promotion looks in an arbitrary namespace/environment git repository

**Pull request merged**
